FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y \
    build-essential \
    libsodium-dev \
    libffi-dev \
    libnacl-dev \
    python3-dev \
    && python3 -m pip install -U discord.py[voice] \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

RUN export PATH=/root/.local/bin:$PATH

CMD ["/bin/bash"]
