version: '3.8'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'toru-db:/data/db'
    command: '--quiet'
    logging:
      driver: none
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      - MONGODB_URL=mongodb
    volumes:
      - '.:/app'
    links:
      - mongodb
volumes:
  toru-db:
