version: '3.3'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'toru-db:/data/db'
    command: '--quiet'
    logging:
      driver: none
  bot:
    image: 'puh00/toru-bot:latest'
    env_file: ./.env
    environment:
      - MONGODB_URL=mongodb
    links:
      - mongodb
volumes:
  toru-db:
